import React from 'react';
import { useLanguage } from '../context/LanguageContext';
import { FileText, ChevronLeft } from 'lucide-react';
import { motion } from 'motion/react';

interface TermsScreenProps {
  onBack: () => void;
}

export default function TermsScreen({ onBack }: TermsScreenProps) {
  const { t, language } = useLanguage();

  const isBn = language === 'bn';

  return (
    <div className="h-full overflow-y-auto px-4 py-8 md:px-8">
      <div className="max-w-4xl mx-auto">
        <motion.button
          initial={{ opacity: 0, x: -10 }}
          animate={{ opacity: 1, x: 0 }}
          onClick={onBack}
          className="flex items-center gap-2 text-[var(--text-muted)] hover:text-[var(--text)] mb-8 transition-colors group"
        >
          <div className="p-1.5 rounded-lg bg-[var(--card)] border border-[var(--border)] group-hover:border-primary/50 transition-all">
            <ChevronLeft size={18} />
          </div>
          <span className="font-medium">{isBn ? 'পিছনে যান' : 'Go Back'}</span>
        </motion.button>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-[var(--card)] border border-[var(--border)] rounded-3xl p-6 md:p-10 shadow-sm relative overflow-hidden"
        >
          <div className="absolute top-0 right-0 p-8 opacity-5">
            <FileText size={120} />
          </div>

          <h1 className="text-3xl md:text-4xl font-display font-bold mb-6 tracking-tight text-[var(--text)]">
            {t.termsOfService}
          </h1>

          <div className="prose prose-slate dark:prose-invert max-w-none space-y-6 text-[var(--text-muted)] leading-relaxed">
            <section>
              <h2 className="text-xl font-bold text-[var(--text)] mb-3">
                {isBn ? '১. পরিষেবার শর্তাদি গ্রহণ' : '1. Acceptance of Terms'}
              </h2>
              <p>
                {isBn 
                  ? 'Nexara AI ব্যবহার করার মাধ্যমে আপনি আমাদের এই পরিষেবার শর্তাবলী মেনে নিচ্ছেন বলে গণ্য হবে। আপনি যদি এই শর্তগুলোর কোনোটির সাথে একমত না হন, তবে দয়া করে এই অ্যাপ্লিকেশনটি ব্যবহার করবেন না।'
                  : 'By using Nexara AI, you are deemed to have accepted these Terms of Service. If you do not agree with any of these terms, please do not use this application.'}
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[var(--text)] mb-3">
                {isBn ? '২. এআই কন্টেন্টের সীমাবদ্ধতা' : '2. AI Content Limitations'}
              </h2>
              <p>
                {isBn
                  ? 'Nexara AI একটি কৃত্রিম বুদ্ধিমত্তা চালিত সিস্টেম। এটি ভুল তথ্য বা ভুল উত্তর প্রদান করতে পারে। যেকোনো গুরুত্বপূর্ণ কাজে এআই-এর দেওয়া তথ্য ব্যবহারের আগে তা পুনরায় যাচাই করে নেওয়া আপনার দায়িত্ব। এআই-এর দেওয়া কোনো তথ্যের জন্য আমরা আইনত দায়ী নই।'
                  : 'Nexara AI is an AI-powered system. It may provide inaccurate or misleading information. It is your responsibility to verify any information provided by the AI before using it for critical tasks. We are not legally responsible for any information generated by the AI.'}
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[var(--text)] mb-3">
                {isBn ? '৩. নিষিদ্ধ ব্যবহার' : '3. Prohibited Uses'}
              </h2>
              <p>
                {isBn
                  ? 'আপনি এই পরিষেবাটি কোনো অবৈধ কাজে, কাউকে হয়রানি করতে, বা ক্ষতিকর কন্টেন্ট জেনারেট করতে ব্যবহার করতে পারবেন না। এই ধরনের অপব্যবহারের ফলে আপনার অ্যাকাউন্ট যেকোনো সময় বাতিল করা হতে পারে।'
                  : 'You may not use this service for any illegal purposes, to harass anyone, or to generate harmful content. Any such abuse may lead to the immediate termination of your account.'}
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[var(--text)] mb-3">
                {isBn ? '৪. দায়মুক্তি (Disclaimer)' : '4. Liability Disclaimer'}
              </h2>
              <p>
                {isBn
                  ? 'এই পরিষেবাটি "যেমন আছে" (As-Is) ভিত্তিতে প্রদান করা হচ্ছে। আমরা এর নিরবচ্ছিন্ন কার্যকারিতার কোনো গ্যারান্টি দিই না। আপনার ডেটা লস বা এই পরিষেবা ব্যবহারের ফলে উদ্ভূত কোনো সমস্যার জন্য Nexara AI দায়বদ্ধ থাকবে না।'
                  : 'This service is provided on an "As-Is" basis. We do not guarantee its uninterrupted operation. Nexara AI will not be liable for any data loss or issues arising from the use of this service.'}
            </p>
            </section>

            <div className="pt-8 mt-8 border-t border-[var(--border)] text-sm italic">
              {isBn 
                ? 'সর্বশেষ আপডেট: ২৬ সেপ্টেম্বর, ২০২৬' 
                : 'Last Updated: September 26, 2026'}
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
